FROM zavalit/java-jdk

MAINTAINER Seva Dolgopolov
ENV LAST-UPDATE 25.02.2016
ENV KAFKA_VER 0.9.0.1
ENV SCALA_VER 2.11


RUN apt-get install -y zookeeper wget supervisor dnsutils && \
    rm -rf /var/lib/apt/lists/* && \
    wget -q http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VER"/kafka_"$SCALA_VER"-"$KAFKA_VER".tgz -O /tmp/kafka_"$SCALA_VER"-"$KAFKA_VER".tgz && \
    tar xfz /tmp/kafka_"$SCALA_VER"-"$KAFKA_VER".tgz -C /opt && \
    rm /tmp/kafka_"$SCALA_VER"-"$KAFKA_VER".tgz

RUN curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > /usr/local/bin/sbt \
  && chmod 0755 /usr/local/bin/sbt

ENV KAFKA_HOME /opt/kafka_"$SCALA_VER"-"$KAFKA_VER"
ADD kafak-start /usr/local/bin/kafka-start

RUN chmod +x /usr/local/bin/kafka-start
