#!/bin/bash
KAFKA=$KAFKA_HOME


#start kafka
mkdir $KAFKA/logs
$KAFKA/bin/zookeeper-server-start.sh $KAFKA/config/zookeeper.properties > $KAFKA/logs/zookeeper.log 2>&1 &
$KAFKA/bin/kafka-server-start.sh $KAFKA/config/server.properties > $KAFKA/logs/kafka.log 2>&1 &

#start server
$JAVA_HOME/bin/java -jar /root/kafka-rest-server-assembly-$SERVER_VER.jar


